export default {
  SIGN_UP_REQUESTING: 'SIGN_UP_REQUESTING',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_REQUEST_ERROR: 'SIGN_UP_REQUEST_ERROR',
  SIGN_IN_REQUESTING: 'SIGN_IN_REQUESTING',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_REQUEST_ERROR: 'SIGN_IN_REQUEST_ERROR',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  NOTIFICATION_ADD_NEW: 'NOTIFICATION_ADD_NEW',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
  USER_CHECK_AUTHENTICATED: 'USER_CHECK_AUTHENTICATED',
};
