export default {
  APIURL: 'http://localhost:8080/',
  signInUrl: 'signin',
  authCustomTypeUrl: 'auth',
  signUpUrl: 'signup',
  logOutUrl: 'logout',
  getPersonalChatsUrl: 'personalChats',
  createChatUrl: 'personalChat',
  sendMessageUrl: 'message',
  loadMessagesUrl: 'messages',
  getUserDataUrl: 'users',
  getFriendsUrl: 'friends',
  searchUsersUrl: 'users/search',
  addToFriendsUrl: 'sendFriendRequests',
  sendRequestToFriendsUrl: 'sendFriendRequests',
  getFriendRequetsUrl: 'friends/requests/income',
  deleteFriendsUrl: 'deleteFriends',
  addNewEventUrl: 'events',
  getEventsOfRangeUrl: 'events',
  deleteEventUrl: 'events',
  chatSocketNamespace: 'http://localhost:8080/chat/',
};
