export default {
  APIURL: 'http://s.q-man.ru:5005/',
  signInUrl: 'signin',
  signUpUrl: 'signup',
  logOutUrl: 'logout',
  getPersonalChatsUrl: 'personalChats',
  createChatUrl: 'personalChat',
  sendMessageUrl: 'message',
  loadMessagesUrl: 'messages',
  getUserDataUrl: 'users',
  getFriendsUrl: 'friends',
  searchUsersUrl: 'users/search',
  addToFriendsUrl: 'sendFriendRequests',
  sendRequestToFriendsUrl: 'sendFriendRequests',
  getFriendRequetsUrl: 'friends/requests/income',
  deleteFriendsUrl: 'deleteFriends',
};
