export default {
  SIGN_UP_REQUESTING: 'SIGN_UP_REQUESTING',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_REQUEST_ERROR: 'SIGN_UP_REQUEST_ERROR',
  SIGN_IN_REQUESTING: 'SIGN_IN_REQUESTING',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_REQUEST_ERROR: 'SIGN_IN_REQUEST_ERROR',
  USER_CHECK_AUTHENTICATED: 'USER_CHECK_AUTHENTICATED',
};
