export default {
  SIGN_UP_REQUESTING: 'SIGN_UP_REQUESTING',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  REQUEST_ERROR: 'REQUEST_ERROR',
  USER_CHECK_AUTHENTICATED: 'USER_CHECK_AUTHENTICATED',
};
